/**
 * @file TypeScript SDK for interacting with the Canton Dark Pool application.
 *
 * This client provides a convenient way to connect to a Canton ledger's JSON API
 * and interact with the dark pool smart contracts. It handles submitting orders,
 * querying for matches, and consenting to trades.
 *
 * It is designed to be used in a Node.js environment or a web frontend.
 */

// This SDK uses the fetch API, which is available in modern Node.js (v18+) and browsers.
// For older Node versions, a polyfill like `node-fetch` would be required.

/**
 * Configuration for the DarkPoolClient.
 */
export interface DarkPoolClientConfig {
  /** The hostname or IP address of the Canton participant's JSON API. */
  host: string;
  /** The port number of the JSON API. */
  port: number;
  /** The party ID of the client user submitting orders. */
  party: string;
  /** The party ID of the trusted dark pool operator running the matching engine. */
  operator: string;
  /** A valid JWT for authenticating with the JSON API, scoped with actAs for the client party. */
  token: string;
}

/**
 * Represents the side of an order. This must match the Daml data type definition.
 */
export type OrderSide = "Buy" | "Sell";

/**
 * Details required to submit a new sealed order.
 * All numeric values are represented as strings to preserve Daml's Decimal precision.
 */
export interface OrderDetails {
  /** The unique identifier for the financial instrument (e.g., 'AAPL', 'ISIN'). */
  instrument: string;
  /** The total quantity of the instrument to trade. */
  quantity: string;
  /** The limit price for the order. A buy order will match at or below this price; a sell will match at or above. */
  price: string;
  /** The side of the order, either 'Buy' or 'Sell'. */
  side: OrderSide;
  /** The minimum acceptable quantity to be filled in a single match. */
  minQuantity: string;
}

/**
 * Generic representation of an active Daml contract from the JSON API v1 query response.
 */
export interface DamlContract<T> {
  contractId: string;
  templateId: string;
  payload: T;
  agreementText: string;
  signatories: string[];
  observers: string[];
}

/**
 * The payload of a `DarkPool.MatchingEngine:SealedOrder` contract.
 */
export interface SealedOrderPayload {
  owner: string;
  operator: string;
  instrument: string;
  quantity: string;
  price: string;
  side: OrderSide;
  minQuantity: string;
  orderId: string; // A unique identifier generated by the contract
  submissionTime: string; // ISO 8601 format timestamp (e.g., "2024-01-01T12:00:00Z")
}

/**
 * The payload of a `DarkPool.MatchedTrade:MatchedTrade` contract.
 */
export interface MatchedTradePayload {
  buyer: string;
  seller: string;
  operator: string;
  instrument: string;
  quantity: string;
  price: string;
  tradeId: string;
  buyerConsented: boolean;
  sellerConsented: boolean;
  matchTime: string; // ISO 8601 format timestamp
}

/**
 * The payload of a `DarkPool.AtomicSettlement:SettlementInstruction` contract.
 */
export interface SettlementInstructionPayload {
    trade: MatchedTradePayload;
    // This could be expanded to include settlement agent details, e.g., CSD, custodians.
}


/**
 * A client for interacting with the dark pool Daml contracts over the JSON API.
 */
export class DarkPoolClient {
  private readonly config: DarkPoolClientConfig;
  private readonly baseUrl: string;
  private readonly headers: Record<string, string>;

  /**
   * Creates an instance of the DarkPoolClient.
   * @param config - The connection and authentication configuration.
   */
  constructor(config: DarkPoolClientConfig) {
    this.config = config;
    this.baseUrl = `http://${config.host}:${config.port}`;
    this.headers = {
      'Authorization': `Bearer ${config.token}`,
      'Content-Type': 'application/json',
    };
  }

  /**
   * Submits a new sealed order to the dark pool.
   * @param details - The details of the order to submit.
   * @returns The result of the create command from the ledger.
   */
  public async submitSealedOrder(details: OrderDetails): Promise<unknown> {
    const command = {
      templateId: "DarkPool.MatchingEngine:SealedOrder",
      payload: {
        owner: this.config.party,
        operator: this.config.operator,
        ...details,
      },
    };

    return this.sendCommand('create', command);
  }

  /**
   * Fetches all active sealed orders for the client's party.
   * @returns A promise that resolves to an array of active `SealedOrder` contracts.
   */
  public async getActiveSealedOrders(): Promise<DamlContract<SealedOrderPayload>[]> {
    const query = {
      templateIds: ["DarkPool.MatchingEngine:SealedOrder"],
    };
    const response = await this.sendCommand('query', query);
    return response.result as DamlContract<SealedOrderPayload>[];
  }

  /**
   * Fetches pending matched trades that require consent from the client's party.
   * @returns A promise that resolves to an array of `MatchedTrade` contracts awaiting consent.
   */
  public async getPendingMatchedTrades(): Promise<DamlContract<MatchedTradePayload>[]> {
    const query = {
      templateIds: ["DarkPool.MatchedTrade:MatchedTrade"],
    };
    const response = await this.sendCommand('query', query);
    const allMatches = response.result as DamlContract<MatchedTradePayload>[];

    // Filter for trades where this party is a counterparty and has not yet consented.
    return allMatches.filter(trade => {
      const { payload } = trade;
      const isBuyer = payload.buyer === this.config.party;
      const isSeller = payload.seller === this.config.party;
      return (isBuyer && !payload.buyerConsented) || (isSeller && !payload.sellerConsented);
    });
  }

  /**
   * Consents to a matched trade, signaling readiness to settle.
   * This is an idempotent action on the contract.
   * @param contractId - The contract ID of the `MatchedTrade` to consent to.
   * @returns The result of the exercise command from the ledger.
   */
  public async consentToTrade(contractId: string): Promise<unknown> {
    const command = {
      templateId: "DarkPool.MatchedTrade:MatchedTrade",
      contractId,
      choice: "ConsentToSettle",
      argument: {}, // Assuming the choice takes no arguments
    };
    return this.sendCommand('exercise', command);
  }

  /**
   * Fetches all completed settlement instructions visible to the client's party.
   * This indicates that a trade has been fully consented by both parties.
   * @returns A promise that resolves to an array of `SettlementInstruction` contracts.
   */
  public async getCompletedSettlements(): Promise<DamlContract<SettlementInstructionPayload>[]> {
    const query = {
        templateIds: ["DarkPool.AtomicSettlement:SettlementInstruction"],
    };
    const response = await this.sendCommand('query', query);
    return response.result as DamlContract<SettlementInstructionPayload>[];
  }

  /**
   * A private helper to send commands to the JSON API and handle responses robustly.
   * @param endpoint - The API endpoint to target ('create', 'query', 'exercise').
   * @param body - The JSON body for the request.
   * @returns The parsed JSON response from the API.
   */
  private async sendCommand(endpoint: 'create' | 'query' | 'exercise', body: object): Promise<any> {
    const url = `${this.baseUrl}/v1/${endpoint}`;
    try {
      const response = await fetch(url, {
        method: 'POST',
        headers: this.headers,
        body: JSON.stringify(body),
      });

      const responseBody = await response.text();

      if (!response.ok) {
        // The JSON API often returns structured errors, try to parse them.
        let errorDetails = responseBody;
        try {
            const parsedError = JSON.parse(responseBody);
            errorDetails = JSON.stringify(parsedError, null, 2);
        } catch (e) {
            // Ignore if body is not JSON
        }
        throw new Error(`JSON API request to ${url} failed with status ${response.status}:\n${errorDetails}`);
      }

      return JSON.parse(responseBody);
    } catch (error) {
      console.error(`Error sending command to ${url}:`, error);
      // Re-throw to allow the caller to handle it
      throw error;
    }
  }
}